blog(updated)/flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

blog(updated)/flaskblog/main/routes.py
from flask import render_template, request, Blueprint, flash, redirect, url_for, render_template, jsonify
from ..models import Post, PushSubscription
from werkzeug.utils import secure_filename
from flask.helpers import send_from_directory
import os
from .. import db
from ...webpush_handler import trigger_push_notifications_for_subscriptions

path = os.path.abspath(os.getcwd())

UPLOAD_FOLDER = r"flaskblog\static\files"
ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif', 'zip'}

path = os.path.join(path, UPLOAD_FOLDER)
print(path)
main = Blueprint('main', __name__)


@main.route("/")
@main.route("/index")
def index():
    return render_template('edited.html', title='Index')


@main.route("/blog/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)


@main.route("/about")
def about():
    return render_template('about.html', title='About')


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@main.route('/files', methods=['GET', 'POST'])
def upload_file():
    f = None
    filename = ''
    filenames = [fname for fname in os.listdir(path) if os.path.isfile(os.path.join(path, fname))]
    if request.method == 'POST':
        # check if the post request has the file part
        if 'file' not in request.files:
            flash('No file chosen')
            return redirect(request.url)
        file = request.files['file']
        # if user does not select file, browser also
        # submit an empty part without filename
        if file.filename == '':
            flash('No selected file')
            return redirect(request.url)
        if allowed_file(file.filename):
            if file:
                filename = secure_filename(file.filename)
                # fname=Add_Filename(text=filename)
                # db.session.add(fname)
                # db.session.commit()
                file_path = os.path.join(path, filename)
                file.save(file_path)

                flash('Your file is uploaded successfully', category='message')
        else:
            flash('Selected file is not permitted')
    return render_template('files.html', name=filenames)


@main.route('/<filename>', methods=['GET', 'POST'])
def download(filename):
    return send_from_directory(path, filename=filename, as_attachment=True)


@main.route("/api/push-subscriptions", methods=["POST"])
def create_push_subscription():
    json_data = request.get_json()
    subscription = PushSubscription.query.filter_by(
        subscription_json=json_data['subscription_json']
    ).first()
    if subscription is None:
        subscription = PushSubscription(
            subscription_json=json_data['subscription_json']
        )
        db.session.add(subscription)
        db.session.commit()
    return jsonify({
        "status": "success"
    })


@main.route("/admin")
def admin_page():
    return render_template("admin.html")


@main.route("/admin-api/trigger-push-notifications", methods=["POST"])
def trigger_push_notifications():
    json_data = request.get_json()
    subscriptions = PushSubscription.query.all()
    results = trigger_push_notifications_for_subscriptions(
        subscriptions,
        json_data.get('title'),
        json_data.get('body')
    )
    return jsonify({
        "status": "success",
        "result": results
    })

blog(updated)/flaskblog/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from .. import db
from ..models import Post
from ..posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post',
                           form=form, legend='New Post')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

blog(updated)/flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flaskblog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='images/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

blog(updated)/flaskblog/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

blog(updated)/flaskblog/templates/edited.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script
    src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <!-- <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}"> -->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>VJTI-Home</title>
</head>
<body style="background: #d53369;  /* fallback for old browsers */
background: -webkit-linear-gradient(to right, #cbad6d, #d53369);  /* Chrome 10-25, Safari 5.1-6 */
background: linear-gradient(to right, #cbad6d, #d53369); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
 color: rgb(80, 37, 37) !important;">
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top" style="background-image: linear-gradient(to top, #30cfd0 0%, #330867 100%) !important;z-index: 20000 !important;">
            <a class="navbar-brand" href="/" id="navE1">VEERMATA JIJABAI TECHNOLOGICAL INST.</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto" style="margin-left: 50px;">
                <li class="nav-item active" style="margin-inline-start: 10 px;">
                    <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item" style="margin-inline: 10px;">
                    <a class="nav-link" href="{{ url_for('main.home') }}">VJTI Blog</a>
                </li>
                <li class="nav-item dropdown" style="margin-inline: 10px;">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    More
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{{ url_for('users.account') }}">Students</a>
                    <a class="dropdown-item" href="/files">Files</a>
                    <a class="dropdown-item" href="#">Faculties</a>
                    <!-- <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a> -->
                    </div>
                </li>
                <li class="nav-item" style="margin-inline: 10px;">
                    <a class="nav-link" href="#">About</a>
                </li>
                </ul>
            </div>
            <!-- <ul>
                <li><a href="{{ url_for('main.index') }}"><i class="fas fa-house-user"></i>  Home</a></li>
                <li><a href="#"><i class="fas fa-university"></i>  My Classroom</a></li>
                <li><a href="#"><i class="fas fa-link"></i>  Departments</a></li>
                <li><a href="#"><i class="fas fa-stream"></i>  News</a></li>
                <li><a href="#"><i class="fas fa-calendar-week"></i>  Calendar</a></li>
                <li><a href="#"><i class="fas fa-user-graduate"></i>  Student</a></li>
                <li><a href="#"><i class="fas fa-sliders-h"></i>  Events</a></li>
                <li><a href="{{ url_for('main.home') }}"><i class="far fa-envelope"></i>  Blogs</a></li>
                <li><a href="#"><i class="fas fa-list-ol"></i>  Lost & Found</a></li>
                <li><a href="{{ url_for('users.account') }}"><i class="fas fa-user"></i>  My Account</a></li>
            </ul> -->
        </nav>
    </header>
    <img src="{{ url_for('static', filename='vjti-main.jpg') }}" id="mainimg">
  <button type="button" class="btn btn-lg btn-block" id="Ebutton"><a href="#jb1" style="text-decoration: none;">Explore VJTI</a></button>
  <div class="jumbotron" id="jb1">
    <h1 class="display-3">Welcome to VJTI</h1>
    <p class="lead">VJTI Mumbai has pioneered India's Engineering and Technology education, research and training since 1887 as Victoria Jubilee Technical Institute. Pre-independence, VJTI had been instrumental in driving Industry 2.0 throughout united India. Post-independence, VJTI played a pivotal role in setting up IITs and RECs of India and strengthened engineering and technology excellence of country through Industry 3.0. In 1997, VJTI name is changed to Veermata Jijabai Technological Institute to honor mother of Chhatrapati Shivaji Maharaj.</p>
  </div>
    <!--<div class="container home_body">
        <h1>VJTI</h1>
        <h3>Veermata Jijabai Technological Institute(Mumbai)<br>वीरमाता  जिजाबाई  तंत्रज्ञान  संस्था ( मुंबई )</h3>
    </div>-->
    <!-- <img href="{{ url_for('static', filename='vjti_large.jpg') }}" id="mainimg">
    <div class="container home_text">
        <div class="row">
            <div class="col-sm-2 dbox"><img href="{{ url_for('static', filename='vjtilogo.jpg') }}" id="logoimg"></div>
            <div class="col-sm-7 text">
                <p>VJTI Mumbai has pioneered India's Engineering and Technology education, research and training since 1887 as Victoria Jubilee Technical Institute. Pre-independence, VJTI had been instrumental in driving Industry 2.0 throughout united India. Post-independence, VJTI played a pivotal role in setting up IITs and RECs of India and strengthened engineering and technology excellence of country through Industry 3.0. In 1997, VJTI name is changed to Veermata Jijabai Technological Institute to honor mother of Chhatrapati Shivaji Maharaj.</p>
                <p>Located in South Mumbai, VJTI is an autonomous institution of repute, owned by Maharashtra State Government.</p>
            </div>
            <div class="col-sm-3 notifications">
                <h3>Notifications</h3>
            </div>
        </div>
    </div> -->
    
    <div class="jumbotron">
        <ul class="navbar-nav mr-auto" style="font-size: medium; ">
            <li> <a class="nav-link" href="#">RTI</a> </li>
            <li> <a class="nav-link" href="#">Location Roadmap</a></li>
            <li> <a class="nav-link" href="#">Contact Us</a></li>
            <li> <a class="nav-link" href="/#">Sitemap</a></li>
            <li> <a class="nav-link" href="#">Disclaimer</a></li>
        </ul>
        <p>More info</p>
        <p><span style="color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal;">Copyright © Team Ultimatrix. All Rights Reserved.
        </span></p>
        <p>Website Developed by Team Ultimatrix</p>
    </div>
<!--     
    <script href="{{ url_for('static', filename='jquery.js') }}"></script>
    <script href="{{ url_for('static', filename='bootstrap.min.js') }}"></script> -->
{#    <script src="https://kit.fontawesome.com/a076d05399.js"></script>#}
</body>
</html>

blog(updated)/flaskblog/templates/files.html
{% extends "layout.html" %} {% block content %}
  <form class="container jumbotron form-group" form method=post enctype=multipart/form-data style="position: relative; top: 5%;background-color: #e7a7a070;">
    <h1 class="display-3">Upload a File</h1>
    <input type=file name=file class="btn btn-primary bg-dark">
    <input type=submit value=Upload class="btn btn-primary bg-dark">
  </form>
  {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}
      <div class="container alert alert-warning alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <strong>{{ message }}</strong> 
      </div>
      <script>
        $(".alert").alert();
      </script>
      {% endfor %}
    {% endif %}
  {% endwith %}
  <button type="submit" class="container btn btn-primary bg-dark" style="position: relative; top: 68%; margin-left: 0%;text-decoration: none !important;color: rgb(255, 255, 255) !important;"><a href='{{url_for('main.upload_file')}}'>View / Refresh</a></button>
  <div class="container list-group" ></div>
  {%for filename in name %}
    <a href='{{url_for('main.download',filename=filename)}}' class="container list-group list-group-item list-group-item-action active" id="filelist" style="margin-top: 2px;">
      {{filename}}
    </a>
  {%endfor%}
{% endblock content %}

blog(updated)/flaskblog/templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='images/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%d %m %Y') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content|truncate(150) }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}

blog(updated)/flaskblog/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script
    src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    {% if title %}
        <title>VJTI Blog - {{ title }}</title>
    {% else %}
        <title>VJTI Blogs</title>
    {% endif %}
</head>
<body style="background: #d53369;  /* fallback for old browsers */
background: -webkit-linear-gradient(to right, #cbad6d, #d53369);  /* Chrome 10-25, Safari 5.1-6 */
background: linear-gradient(to right, #cbad6d, #d53369); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
">
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top" style="background-image: linear-gradient(to top, #30cfd0 0%, #330867 100%) !important;z-index: 20000 !important;">
        <div class="container">
          <a class="navbar-brand mr-4" href="{{ url_for('main.home') }}">VJTI Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="/">Back to Site</a>
              <a class="nav-item nav-link" href="/files">Files</a>
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>My DAshboard</h3>
            <p class='text-muted'>Recent Notifications
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Notification 1</li>
                <li class="list-group-item list-group-item-light">Notification 1</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
		type="text/javascript"
		src="/static/register_service_worker.js">
	</script>
	<script type="text/javascript">
		registerServiceWorker(
			"/static/service_worker.js",
			"{{config['VAPID_PUBLIC_KEY']}}",
			"/api/push-subscriptions"
		);
	</script>
</body>
</html>

blog(updated)/flaskblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

blog(updated)/flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
      <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='images/' + post.author.image_file) }}">
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            {% if post.author == current_user %}
              <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
              </div>
            {% endif %}
          </div>
          <h2 class="article-title">{{ post.title }}</h2>
          <p class="article-content">{{ post.content }}</p>
        </div>
      </article>
      <!-- Modal -->
      <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Delete this Post?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">No don't Delete</button>
              <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Yes Delete">
              </form>
            </div>
          </div>
        </div>
      </div>
{% endblock content %}